impred/ds_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('impred.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

impred/user/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                          success_url='/user/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
]

impred/user/models.py
# Create your models here.
# from django.contrib.auth.models import AbstractUser
# from django.db import models


# class СustomUser(AbstractUser):
#     username = models.CharField(max_length=30, null=False)
#     email = models.EmailField(unique=True)
#     password = models.CharField(max_length=128)

#     def __str__(self):
#         return self.username

impred/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())
    
    email = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

impred/user/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy

from .forms import RegisterForm, LoginForm


def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='impred:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='impred:main')
        else:
            return render(request, 'user/signup.html', context={"form": form})

    return render(request, 'user/signup.html', context={"form": RegisterForm()})

def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='impred:main')

    if request.method == 'POST':
        print(f"request.method == 'POST'")
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            print(f"Username or password didn\'t match")
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='user:login')

        login(request, user)
        return redirect(to='impred:main')

    return render(request, 'user/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='impred:main')


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'user/password_reset.html'
    email_template_name = 'user/password_reset_email.html'
    html_email_template_name = 'user/password_reset_email.html'
    success_url = reverse_lazy('user:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'user/password_reset_subject.txt'

impred/user/templates/user/login.html
{% extends "impred/base.html" %}

{% block content %}

<!-- Login content start -->

<div class="login-hero">
    <div class="login-container1">
        <img
            alt="image"
            src="https://img.freepik.com/free-vector/blue-futuristic-networking-technology_53876-100679.jpg?w=900&amp;t=st=1707929845~exp=1707930445~hmac=e84e7e2f3ef6d1f2a3d4583c5e6f880f752b21f3c080c7cf0ce26daa2b201e1a"
            class="login-image"
        />
    </div>
    <div class="login-container2">
        <div class="login-container3">
            <h1 class="login-text">Wellcome to YASO</h1>

            <!-- Form login -->
            <form action="{% url 'user:login' %}" method="post" class="login-form">
                {% csrf_token %}

                {% if messages %}
                <div>
                    {% for message in messages %}
                    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
                    {% endfor %}
                </div>
                {% endif %}
                
                <div class="login-textinput">
                    <label>Username
                        <div class="input">
                            {{ form.username }}
                        </div>
                    </label>
                </div>
            
                <div class="login-textinput">
                    <label for="username">Password
                        <div class="input">
                            {{ form.password }}
                        </div>
                    </label>
                </div>
                        
                <div class="login-btn-group">
                    <button type="submit" class="login-button button">Submit</button>
                    <button type="reset" class="login-button1 button">Reset</button>
                </div>
            </form>

        </div>
    </div>
</div>

<!-- Login content end -->

{% endblock %}

impred/user/templates/user/signup.html
{% extends "impred/base.html" %}

{% block content %}

<div class="login-hero">
    <div class="login-container1">
        <img
            alt="image"
            src="https://img.freepik.com/free-vector/blue-futuristic-networking-technology_53876-100679.jpg?w=900&amp;t=st=1707929845~exp=1707930445~hmac=e84e7e2f3ef6d1f2a3d4583c5e6f880f752b21f3c080c7cf0ce26daa2b201e1a"
            class="login-image"
        />
    </div>
    <div class="login-container2">
        <div class="signup-container3">
            <h1 class="login-text">Wellcome to YASO</h1>

            <form action="{% url 'user:signup' %}" method="post" class="login-form">
                {% csrf_token %}

                <div class="login-textinput">
                    <label> Username:
                        <div class="input">
                            {{ form.username }}
                        </div>
                    </label>
                    <span class="alert-error">{{ form.errors.username }}</span>
                </div>

                <div class="login-textinput">
                    <label> Email:
                        <div class="input">
                            {{ form.email }}
                        </div>
                    </label>
                    <span class="alert-error">{{ form.errors.email }}</span>
                </div>

                <br>
                <div class="login-textinput">
                    <label> Password:
                        <div class="input">
                            {{ form.password1 }}
                        </div>
                    </label>
                    <span class="alert-error">{{ form.errors.password1 }}</span>
                </div>

                <div class="login-textinput">
                    <label> Password confirmation:
                        <div class="input">
                            {{ form.password2 }}
                        </div>
                    </label>
                    <span class="alert-error">{{ form.errors.password2 }}</span>
                </div>

                <div class="login-btn-group">
                    <button type="submit" class="login-button button">Submit</button>
                    <button type="reset" class="login-button1 button">Reset</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}