impred/ds_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('impred.urls')),
    path('user/', include('user.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

impred/impred/urls.py
from django.urls import path

from . import views

app_name = 'impred'

urlpatterns = [
    # path('', views.index, name='index'),
    path('', views.main, name='main'),
    path('loadimage/', views.loadimage, name='loadimage'),
    path('predictimage/', views.predictimage, name='predictimage'),
    path('netmodels/', views.netmodels, name='netmodels'),
    path('netmodel/', views.netmodel, name='netmodel'),
    path('netmodel/<int:id>', views.netmodel, name='netmodel'),
    # path('labels/', views.labels, name='labels'),
    # path('label/<int:netmodel_id>', views.label, name='label'),
]

impred/user/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='user/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='user/password_reset_confirm.html',
                                          success_url='/user/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='user/password_reset_complete.html'),
         name='password_reset_complete'),
]

impred/impred/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


# from user.models import СustomUser


# Create your models here.
class NetModels(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)     # Наименование модели
    description = models.CharField(max_length=150, null=False)          # Описание модели
    created = models.DateTimeField(auto_now_add=True)
    modelpath = models.FileField(upload_to='models/', null=False)       # Путь к файлу загруженной модели
    accuracy = models.FloatField(null=False)                            # Достигнутая точность модели
    categories = models.IntegerField(null=False)                        # Количество категорий предсказания модели
    
    def __str__(self):
        return f"{self.name}"


# class_names = ['Airplane', 'Automobile', 'Bird', 'Cat', 'Deer', 'Dog', 'Frog', 'Horse', 'Ship', 'Truck']
class Labels(models.Model):
    id = models.AutoField(primary_key=True)
    predict_id = models.IntegerField(null=False)                        # Индекс метки в модели
    name = models.CharField(max_length=30, null=False)                  # Наименование метки
    netmodel = models.ForeignKey(NetModels, on_delete=models.CASCADE)   # Модель, для которой эта метка

    def __str__(self):
        return f"{self.name}"

    class Meta:
        unique_together = ('netmodel', 'predict_id',)


class Images(models.Model):
    name = models.CharField(max_length=30, null=False)                              # Наименование картинки
    netmodel = models.ForeignKey(NetModels, on_delete=models.CASCADE, null=True)    # Модель, по которой оценивалась картинка
    predict = models.ForeignKey(Labels, on_delete=models.CASCADE, null=True)        # Категория (метка) предсказания
    created = models.DateTimeField(auto_now_add=True)
    imagepath = models.ImageField(upload_to='images/', null=False)                  #  Путь файлу загруженной картинки
    # user = models.ForeignKey(User, on_delete=models.CASCADE, default=1) # временно закоментировал до момента создания класса User

    def __str__(self):
        return f"{self.name}"

    # resizing images
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.imagepath)

        if img.height > 250 or img.width > 250:
            new_img = (250, 250)
            img.thumbnail(new_img)
            # with open(self.imagepath.path, "wb") as f:
            #     img.save(f)
            img.save(self.imagepath.path)

impred/impred/forms.py
from django import forms

from .models import Images, NetModels, Labels

class ImageForm(forms.ModelForm):
    imagepath = forms.ImageField(widget=forms.FileInput())

    class Meta:
        model = Images
        fields = ['imagepath']


class NetModelForm(forms.ModelForm):
    name = forms.CharField(min_length=3, max_length=30, required=True, widget=forms.TextInput())
    description = forms.CharField(max_length=150, required=False, widget=forms.TextInput())
    modelpath = forms.FileField(widget=forms.FileInput())
    accuracy = forms.FloatField(min_value=0.0, max_value=1.0, required=True, widget=forms.NumberInput())
    categories = forms.IntegerField(min_value=1, required=True, widget=forms.NumberInput())
    # labels = forms.CharField(min_length=2, required=True, widget=forms.TextInput())

    class Meta:
        model = NetModels
        fields = ['name', 'description', 'modelpath', 'accuracy', 'categories']


class LabelForm(forms.ModelForm):
    predict_id = forms.IntegerField(min_value=0, required=True, widget=forms.NumberInput())
    names = forms.CharField(max_length=30, required=True, widget=forms.TextInput())
    netmodel = NetModelForm()

    class Meta:
        model = Labels
        fields = ['netmodel', 'predict_id', 'names']

impred/impred/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .forms import ImageForm, NetModelForm, LabelForm
from .models import Images, NetModels, Labels
from .utils import get_labels_str, get_netmodel_by_name
from .model_cifar10 import predict_image


# Create your views here.
def main(request):
    return render(request, 'impred/index.html', context={'title': "Завантажте свою світлину і я спробую вгадати, що на ній зображено."})


def loadimage(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)

        if form.is_valid():
            new_image = form.save(commit=False)
            #new_image.user = request.user  # предварительно для будущего usera
            new_image.save()

            # Сохранение id новой картинки в сессии
            request.session["new_image_id"] = new_image.id

            # # Предварительно код для анализа images моделью и привязки к классу.
            image_path = new_image.imagepath.path
            # prediction = model_function(image_path)  # предварительно функция для предсказания класса
            # # Получение или создание соответствующей метки (label)
            # label, created = Labels.objects.get_or_create(name=prediction, netmodel=new_image.netmodel)
            label = predict_image(image_path)

            netmodel_name = "SIFAR-10"
            netmodel = get_netmodel_by_name(netmodel_name)            
            predict = Labels.objects.filter(name=label).filter(netmodel=netmodel).first()
            # # Привязка к модели и предсказанию
            new_image.predict = predict
            new_image.save()
            return redirect('impred:predictimage')
    else:
        form = ImageForm()
    return render(request, 'impred/loadimage.html', context={'image_form': form})


def predictimage(request):
    # Получение id новой картинки из сессии
    new_image_id = request.session.get("new_image_id")

    if new_image_id:
        images = Images.objects.filter(id=new_image_id)
        # Удаление new_image_id из сессии
        del request.session["new_image_id"]
    else:
        images = Images.objects.all()
    return render(request, 'impred/predictimage.html', context={'images': images})


def netmodels(request):
    net_models = NetModels.objects.order_by('name').all()
    # print(f">>> netmodels = {net_models}")
    net_labels = []
    for nm in net_models:
        net_labels.append({"netmodel": nm, "labels": get_labels_str(nm.id)})
    # print(f">>> netmodels: {net_labels}")
    return render(request, 'impred/netmodels.html', context={'netmodels': net_labels})


@login_required
def netmodel(request, netmodel_id):
    if request.method == 'POST':
        form = NetModelForm(request.POST, request.FILES)

        if form.is_valid():
            new_model = form.save(commit=False)
            new_model.save()
            return redirect('impred:netmodels')
    else:
        if netmodel_id:
            netmodel = NetModels.objects.get(id=netmodel_id)
            form = NetModelForm(netmodel, instance=NetModels)
        else:
            form = NetModelForm()
    return render(request, 'impred/netmodel.html', context={'form': form})


# def labels(request, netmodel_id):
#     if netmodel_id:
#         labs = Labels.objects.filter(netmodel_id=netmodel_id).all()
#     else:
#         labs = Labels.objects.all()
#     return render(request, 'impred/netmodels.html', context={'labels': labs})


# @login_required
# def label(request, netmodel_id):
#     if request.method == 'POST':
#         form = LabelForm(request.POST)

#         if form.is_valid():
#             new_label = form.save(commit=False)
#             new_label.save()
#             return redirect('impred:labels')
#     else:
#         form = LabelForm()
#     return render(request, 'impred/label.html', context={'form': form})

impred/impred/templates/impred/index.html
{% extends 'impred/base.html' %}

{% block content %}

        <!-- First baner -->

        <div class="home-hero">
            <div class="heroContainer home-hero1">
              <div class="home-container1">
                <h1 class="home-hero-heading heading1">Welcome to YASO Lab</h1>
                <span class="home-text">Discover&nbsp;AI with YASO Lab</span>
               
                <div class="home-btn-group">
                  <a href="{% url 'user:login' %}" class="home-hero-button1 buttonFilled">
                    Get Started
                  </a>
                  <a href="{% url 'user:login' %}" class="home-hero-button2 buttonFlat">
                    Learn More&nbsp;→
                  </a>
                </div>
              </div>
            </div>
          </div>
          <div class="home-faq">
            <div class="home-faq-container faqContainer">
              <div class="home-faq1">
                <div class="home-container2">
                  <span class="overline">
                    <span>MIT LICENSE project</span>
                    <br />
                  </span>
                  <h2 class="home-text18 heading2">YASO</h2>
                  <span class="home-text19">
                    <span>Artificial Intelligence Laboratory</span>
                    <br class="bodyLarge" />
                  </span>
                </div>
                <div class="home-container3">
                  <div class="question1-container">
                    <span class="question1-text">Who we are?</span>
                    <span>
                      <br />
                      <span>
                        YASO Lab - your ideal partner in the world of artificial
                        intelligence and algorithms! The YASO Lab platform is
                        designed to provide access to the most advanced tools and
                        resources for studying and improving skills in these
                        exciting areas.
                      </span>
                      <br />
                      <br />
                      <span>What makes YASO Lab unique?</span>
                      <br />
                      <br />
                      <span>
                        Hands-on learning: With YASO Lab, you can not only
                        theoretically study algorithms but also apply them to
                        real-world tasks. Our practical assignments will help you
                        solidify your knowledge and gain valuable experience in
                        solving real problems.
                      </span>
                      <br />
                      <br />
                      <span>
                        Interactivity: Our platform promotes active learning
                        through interactive elements, data visualization, and the
                        ability to exchange ideas with other community members.
                      </span>
                      <br />
                      <br />
                      <span>
                        Support: The YASO Lab team is always ready to assist you
                        with any questions, provide guidance on educational
                        materials, and help with task solutions.
                      </span>
                      <br />
                      <br />
                      <span>
                        Don't waste time - join YASO Lab today and unleash your
                        potential in the world of artificial intelligence and
                        algorithms!
                      </span>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
  
          <!-- Our team -->
  
          <h1 class="home-text22">YASO team</h1>
          <div class="home-blog">
  
            <div class="blog-post-card41-blog-post-card blog-post-card41-root-class-name1">
              <img
                alt="image"
                src="https://avatars.githubusercontent.com/u/126519662?v=4"
                class="blog-post-card41-image"
              />
              <div class="blog-post-card41-container">
                <span class="blog-post-card41-text">Oleksiy Goryachev</span>
                <div class="blog-post-card41-separator"></div>
                <span class="blog-post-card41-text1">TEAM LEADER</span>
              </div>
            </div>
  
            <div class="home-container4">
  
              <div class="blog-post-card41-blog-post-card blog-post-card41-root-class-name2">
                <img
                  alt="image"
                  src="/media/external/svitlana-1500w.jpg"
                  class="blog-post-card41-image"
                />
                <div class="blog-post-card41-container">
                  <span class="blog-post-card41-text">Svitlana Kovaleva</span>
                  <div class="blog-post-card41-separator"></div>
                  <span class="blog-post-card41-text1">PYTHON DEVELOPER</span>
                </div>
              </div>
              
              <div class="blog-post-card41-blog-post-card blog-post-card41-root-class-name3">
                <img
                  alt="image"
                  src="https://avatars.githubusercontent.com/u/128192015?v=4"
                  class="blog-post-card41-image"
                />
                <div class="blog-post-card41-container">
                  <span class="blog-post-card41-text">Yury Nikitchenko</span>
                  <div class="blog-post-card41-separator"></div>
                  <span class="blog-post-card41-text1">PYTHON DEVELOPER</span>
                </div>
              </div>
  
            </div>
  
            <div class="blog-post-card41-blog-post-card blog-post-card41-root-class-name4">
              <img
                alt="image"
                src="https://avatars.githubusercontent.com/u/13149612?v=4"
                class="blog-post-card41-image"
              />
              <div class="blog-post-card41-container">
                <span class="blog-post-card41-text">Andrii Chychur</span>
                <div class="blog-post-card41-separator"></div>
                <span class="blog-post-card41-text1">PYTHON DEVELOPER</span>
              </div>
            </div>
  
          </div>
  
          <!-- Finis our team -->
  
{% endblock %}

impred/impred/templates/impred/loadimage.html
{% extends "impred/base.html" %}

{% block content %}

<div class="lab-blog">
    <div class="lab-container1">
        <div class="blog-post-card2-blog-post-card blog-post-card2-root-class-name3">
            <img
                alt="image"
                src="https://img.freepik.com/free-vector/graident-ai-robot-vectorart_78370-4114.jpg?w=740&amp;t=st=1707905773~exp=1707906373~hmac=b83638e5fa0d3569c22dd03176cb76b37ed3a4a7adc215a75d41f4ceac7de95c://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;w=1000"
                image_src="https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixid=Mnw5MTMyMXwwfDF8c2VhcmNofDd8fHBvcnRyYWl0fGVufDB8fHx8MTYyNjM3ODk3Mg&amp;ixlib=rb-1.2.1&amp;h=1000"
                class="blog-post-card2-image"
            />
            <div class="blog-post-card2-container">
                <div class="blog-post-card2-container1">
                    <span class="blog-post-card2-text">version 0.1.4</span>
                    <span class="blog-post-card2-text1">accuracy: 87%</span>
                </div>

                <!-- Result of model work (terminal)  -->

                <span class="blog-post-card2-text2">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed
                    non volutpat turpis. Mauris luctus rutrum mi ut rhoncus.
                    Integer in dignissim tortor. Lorem ipsum dolor sit amet,
                    consectetur adipiscing&nbsp; ipsum dolor sit amet, consectetur
                    adipiscing elit. Sed non volutpat turpis. Mauris luctus rutrum
                    mi ut rhoncus. Integer in dignissim tortor. Lorem ipsum dolor
                    sit amet, consectetur adipiscing ..
                </span>


                <div class="blog-post-card2-container2">
                    <div class="blog-post-card2-profile">
                        <img
                            alt="profile"
                            src="https://img.freepik.com/free-vector/graident-ai-robot-vectorart_78370-4114.jpg?w=740&amp;t=st=1707905773~exp=1707906373~hmac=b83638e5fa0d3569c22dd03176cb76b37ed3a4a7adc215a75d41f4ceac7de95c"
                            class="blog-post-card2-image1"
                        />
                        <span class="blog-post-card2-text3">
                            <span class="blog-post-card2-text4">SIFAR-10</span>
                            <br />
                        </span>
                    </div>

                    <form method="post" enctype="multipart/form-data" class="blog-post-card2-textinput" action="{% url 'impred:loadimage' %}">
                        {% csrf_token %}

                        <div class="blog-post-card2-container2">

                            <div class="input">
                                {{ image_form.imagepath }}
                            </div>
                            <span class="alert-error"></span>>{{image_form.errors.imagepath}}</span>

                            <button type="submit" class="blog-post-card2-button button">RUN</button>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

impred/impred/templates/impred/netmodels.html
{% extends "impred/base.html" %}

{% block content %}

<div class="home-hero">
    <!-- <div class="home-faq"> -->
        <!-- <div class="home-faq-container faqContainer"> -->
            <div class="home-faq11">
                <div class="mb-12" style="display: flex;justify-content: space-between;">
                    <h1 style="padding: 0;">Neural Network Models</h1>
                    <!-- {% if user.is_authenticated %}
                    <a class="home-login buttonFilled" href="impred/netmodel_add" role="button" style="margin: 0;">Add NetModel</a>
                    {% endif %} -->
                </div>
                {% for netm in netmodels %}
                <div class="quote">
                    <p><span class="bold">Model:</span> {{netm.netmodel.name}}</p>
                    <p>{{netm.netmodel.description}}</p>
                    <p><span class="bold">Accuracy =</span> {{netm.netmodel.accuracy}}</p>

                    {% if netm.labels %}
                    <p class="bold">Labels:</p>
                    <p>{{netm.labels}}</p>
                    {% endif %}

                    <!-- {% if user.is_authenticated %}
                    <a class="home-login buttonFilled" href="impred/labels/{{netm.id}}" role="button">Labels</a>
                    {% endif %} -->

                </div>
                {% endfor %}
            </div>
        <!-- </div> -->
    <!-- </div> -->
</div>

{% endblock content %}

impred/impred/templates/impred/predictimage.html
{% extends "impred/base.html" %}

{% block content %}

<div class="home-hero">
    <div class="home-faq11">

        <div>
            <h1 class="mb-12">Predict Images</h1>
        </div>

        <div style="display: flex;gap: 12px;flex-wrap: wrap;">
            {% for image in images %}
            <div class="quote">
                <p> "Thits is <span class="bold">{{ image.predict.name }}</span>"</p>
                <img src="/media/{{image.imagepath}}" alt="{{ image.predict.name }}" style="max-width: 100%; max-height: 100%;">
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}